from typing import Any

jlpoint: Any


class Client:
    server: str
    sessionId: str

    def __init__(self, ip_adress: str = ..., port: int = ...) -> None: ...

    def connect(self) -> None: ...

    def disconnect(self) -> None: ...

    def is_creo_running(self) -> bool: ...

    def kill_creo(self) -> Any: ...

    def start_creo(self, path: str, retries: int = ..., use_desktop: bool = ...) -> Any: ...

    def stop_creo(self) -> Any: ...

    def _creoson_post(
            self,
            command: str,
            function: str,
            data: dict[str, Any] | None = ...,
            key_data: str | None = ...,
    ) -> Any: ...

    def bom_get_paths(
            self,
            file_: str | None = ...,
            paths: bool | None = ...,
            skeletons: bool | None = ...,
            top_level: bool | None = ...,
            get_transforms: bool | None = ...,
            exclude_inactive: bool | None = ...,
            get_simpreps: bool | None = ...,
            **kwargs: Any,
    ) -> Any: ...

    def creo_cd(self, dirname: str, **kwargs: Any) -> Any: ...

    def creo_delete_files(self, *args: Any, **kwargs: Any) -> Any: ...

    def creo_get_config(self, *args: Any, **kwargs: Any) -> Any: ...

    def creo_get_std_color(self, *args: Any, **kwargs: Any) -> Any: ...

    def creo_list_dirs(self, *args: Any, **kwargs: Any) -> Any: ...

    def creo_list_files(self, *args: Any, **kwargs: Any) -> Any: ...

    def creo_mkdir(self, *args: Any, **kwargs: Any) -> Any: ...

    def creo_pwd(self, *args: Any, **kwargs: Any) -> Any: ...

    def creo_rmdir(self, *args: Any, **kwargs: Any) -> Any: ...

    def creo_set_config(self, *args: Any, **kwargs: Any) -> Any: ...

    def creo_set_creo_version(self, *args: Any, **kwargs: Any) -> Any: ...

    def creo_set_std_color(self, *args: Any, **kwargs: Any) -> Any: ...

    def dimension_copy(self, *args: Any, **kwargs: Any) -> Any: ...

    def dimension_list_detail(self, *args: Any, **kwargs: Any) -> Any: ...

    def dimension_list(self, *args: Any, **kwargs: Any) -> Any: ...

    def dimension_set(self, *args: Any, **kwargs: Any) -> Any: ...

    def dimension_set_text(self, *args: Any, **kwargs: Any) -> Any: ...

    def dimension_show(self, *args: Any, **kwargs: Any) -> Any: ...

    def dimension_user_select(self, *args: Any, **kwargs: Any) -> Any: ...

    def drawing_add_model(self, *args: Any, **kwargs: Any) -> Any: ...

    def drawing_add_sheet(self, *args: Any, **kwargs: Any) -> Any: ...

    def drawing_create_gen_view(self, *args: Any, **kwargs: Any) -> Any: ...

    def drawing_create(self, *args: Any, **kwargs: Any) -> Any: ...

    def drawing_create_proj_view(self, *args: Any, **kwargs: Any) -> Any: ...

    def drawing_create_symbol(self, *args: Any, **kwargs: Any) -> Any: ...

    def drawing_delete_models(self, *args: Any, **kwargs: Any) -> Any: ...

    def drawing_delete_sheet(self, *args: Any, **kwargs: Any) -> Any: ...

    def drawing_delete_symbol_def(self, *args: Any, **kwargs: Any) -> Any: ...

    def drawing_delete_symbol_inst(self, *args: Any, **kwargs: Any) -> Any: ...

    def drawing_delete_view(self, *args: Any, **kwargs: Any) -> Any: ...

    def drawing_get_cur_model(self, *args: Any, **kwargs: Any) -> Any: ...

    def drawing_get_cur_sheet(self, *args: Any, **kwargs: Any) -> Any: ...

    def drawing_get_num_sheets(self, *args: Any, **kwargs: Any) -> Any: ...

    def drawing_get_sheet_format(self, *args: Any, **kwargs: Any) -> Any: ...

    def drawing_get_sheet_scale(self, *args: Any, **kwargs: Any) -> Any: ...

    def drawing_get_sheet_size(self, *args: Any, **kwargs: Any) -> Any: ...

    def drawing_get_view_loc(self, *args: Any, **kwargs: Any) -> Any: ...

    def drawing_get_view_scale(self, *args: Any, **kwargs: Any) -> Any: ...

    def drawing_get_view_sheet(self, *args: Any, **kwargs: Any) -> Any: ...

    def drawing_is_symbol_def_loaded(self, *args: Any, **kwargs: Any) -> Any: ...

    def drawing_list_models(self, *args: Any, **kwargs: Any) -> Any: ...

    def drawing_list_symbols(self, *args: Any, **kwargs: Any) -> Any: ...

    def drawing_list_view_details(self, *args: Any, **kwargs: Any) -> Any: ...

    def drawing_list_views(self, *args: Any, **kwargs: Any) -> Any: ...

    def drawing_load_symbol_def(self, *args: Any, **kwargs: Any) -> Any: ...

    def drawing_regenerate(self, *args: Any, **kwargs: Any) -> Any: ...

    def drawing_regenerate_sheet(self, *args: Any, **kwargs: Any) -> Any: ...

    def drawing_rename_view(self, *args: Any, **kwargs: Any) -> Any: ...

    def drawing_scale_sheet(self, *args: Any, **kwargs: Any) -> Any: ...

    def drawing_scale_view(self, *args: Any, **kwargs: Any) -> Any: ...

    def drawing_select_sheet(self, *args: Any, **kwargs: Any) -> Any: ...

    def drawing_set_cur_model(self, *args: Any, **kwargs: Any) -> Any: ...

    def drawing_set_sheet_format(self, *args: Any, **kwargs: Any) -> Any: ...

    def drawing_set_view_loc(self, *args: Any, **kwargs: Any) -> Any: ...

    def drawing_view_bound_box(self, *args: Any, **kwargs: Any) -> Any: ...

    def familytable_add_inst(self, *args: Any, **kwargs: Any) -> Any: ...

    def familytable_create_inst(self, *args: Any, **kwargs: Any) -> Any: ...

    def familytable_delete_inst(self, *args: Any, **kwargs: Any) -> Any: ...

    def familytable_delete(self, *args: Any, **kwargs: Any) -> Any: ...

    def familytable_exists(self, *args: Any, **kwargs: Any) -> Any: ...

    def familytable_get_cell(self, *args: Any, **kwargs: Any) -> Any: ...

    def familytable_get_header(self, *args: Any, **kwargs: Any) -> Any: ...

    def familytable_get_parents(self, *args: Any, **kwargs: Any) -> Any: ...

    def familytable_get_row(self, *args: Any, **kwargs: Any) -> Any: ...

    def familytable_list(self, *args: Any, **kwargs: Any) -> Any: ...

    def familytable_list_tree(self, *args: Any, **kwargs: Any) -> Any: ...

    def familytable_replace(self, *args: Any, **kwargs: Any) -> Any: ...

    def familytable_set_cell(self, *args: Any, **kwargs: Any) -> Any: ...

    def feature_delete(self, *args: Any, **kwargs: Any) -> Any: ...

    def feature_delete_param(self, *args: Any, **kwargs: Any) -> Any: ...

    def feature_list(self, *args: Any, **kwargs: Any) -> Any: ...

    def feature_list_params(self, *args: Any, **kwargs: Any) -> Any: ...

    def feature_list_group_features(self, *args: Any, **kwargs: Any) -> Any: ...

    def feature_list_pattern_features(self, *args: Any, **kwargs: Any) -> Any: ...

    def feature_list_selected(self, *args: Any, **kwargs: Any) -> Any: ...

    def feature_param_exists(self, *args: Any, **kwargs: Any) -> Any: ...

    def feature_rename(self, *args: Any, **kwargs: Any) -> Any: ...

    def feature_resume(self, *args: Any, **kwargs: Any) -> Any: ...

    def feature_set_param(self, *args: Any, **kwargs: Any) -> Any: ...

    def feature_suppress(self, *args: Any, **kwargs: Any) -> Any: ...

    def feature_user_select_csys(self, *args: Any, **kwargs: Any) -> Any: ...

    def file_assemble(self, *args: Any, **kwargs: Any) -> Any: ...

    def file_backup(self, *args: Any, **kwargs: Any) -> Any: ...

    def file_close_window(self, *args: Any, **kwargs: Any) -> Any: ...

    def file_display(self, *args: Any, **kwargs: Any) -> Any: ...

    def file_delete_material(self, *args: Any, **kwargs: Any) -> Any: ...

    def file_erase(self, *args: Any, **kwargs: Any) -> Any: ...

    def file_erase_not_displayed(self, *args: Any, **kwargs: Any) -> Any: ...

    def file_exists(self, *args: Any, **kwargs: Any) -> Any: ...

    def file_get_active(self, *args: Any, **kwargs: Any) -> Any: ...

    def file_get_accuracy(self, *args: Any, **kwargs: Any) -> Any: ...

    def file_get_cur_material(self, *args: Any, **kwargs: Any) -> Any: ...

    def file_get_cur_material_wildcard(self, *args: Any, **kwargs: Any) -> Any: ...

    def file_get_fileinfo(self, file_: str | None = ..., **kwargs: Any) -> Any: ...

    def file_get_length_units(self, *args: Any, **kwargs: Any) -> Any: ...

    def file_get_mass_units(self, *args: Any, **kwargs: Any) -> Any: ...

    def file_get_transform(self, *args: Any, **kwargs: Any) -> Any: ...

    def file_has_instances(self, *args: Any, **kwargs: Any) -> Any: ...

    def file_is_active(self, *args: Any, **kwargs: Any) -> Any: ...

    def file_list_instances(self, *args: Any, **kwargs: Any) -> Any: ...

    def file_list_materials(self, *args: Any, **kwargs: Any) -> Any: ...

    def file_list_materials_wildcard(self, *args: Any, **kwargs: Any) -> Any: ...

    def file_list(self, *args: Any, **kwargs: Any) -> Any: ...

    def file_list_simp_reps(self, *args: Any, **kwargs: Any) -> Any: ...

    def file_load_material_file(self, *args: Any, **kwargs: Any) -> Any: ...

    def file_massprops(self, *args: Any, **kwargs: Any) -> Any: ...

    def file_open_errors(self, *args: Any, **kwargs: Any) -> Any: ...

    def file_open(
            self,
            file_: str | list[str],
            dirname: str | None = ...,
            generic: str | None = ...,
            display: bool | None = ...,
            activate: bool | None = ...,
            new_window: bool | None = ...,
            regen_force: bool | None = ...,
    ) -> Any: ...

    def file_postregen_relations_get(self, *args: Any, **kwargs: Any) -> Any: ...

    def file_postregen_relations_set(self, *args: Any, **kwargs: Any) -> Any: ...

    def file_refresh(self, *args: Any, **kwargs: Any) -> Any: ...

    def file_regenerate(self, *args: Any, **kwargs: Any) -> Any: ...

    def file_relations_get(self, *args: Any, **kwargs: Any) -> Any: ...

    def file_relations_set(self, *args: Any, **kwargs: Any) -> Any: ...

    def file_rename(self, *args: Any, **kwargs: Any) -> Any: ...

    def file_repaint(self, *args: Any, **kwargs: Any) -> Any: ...

    def file_save(self, *args: Any, **kwargs: Any) -> Any: ...

    def file_set_cur_material(self, *args: Any, **kwargs: Any) -> Any: ...

    def file_set_length_units(self, *args: Any, **kwargs: Any) -> Any: ...

    def file_set_mass_units(self, *args: Any, **kwargs: Any) -> Any: ...

    def geometry_bound_box(self, *args: Any, **kwargs: Any) -> Any: ...

    def geometry_get_edges(self, *args: Any, **kwargs: Any) -> Any: ...

    def geometry_get_surfaces(self, *args: Any, **kwargs: Any) -> Any: ...

    def interface_export_3dpdf(self, *args: Any, **kwargs: Any) -> Any: ...

    def interface_export_file(self, *args: Any, **kwargs: Any) -> Any: ...

    def interface_export_image(self, *args: Any, **kwargs: Any) -> Any: ...

    def interface_export_pdf(self, *args: Any, **kwargs: Any) -> Any: ...

    def interface_export_program(self, *args: Any, **kwargs: Any) -> Any: ...

    def interface_import_file(
            self,
            filename: str,
            file_type: str | None = ...,
            dirname: str | None = ...,
            new_name: str | None = ...,
            new_model_type: str = ...,
    ) -> str: ...

    def interface_import_program(self, *args: Any, **kwargs: Any) -> Any: ...

    def interface_mapkey(self, *args: Any, **kwargs: Any) -> Any: ...

    def interface_plot(self, *args: Any, **kwargs: Any) -> Any: ...

    def layer_delete(self, *args: Any, **kwargs: Any) -> Any: ...

    def layer_exists(self, *args: Any, **kwargs: Any) -> Any: ...

    def layer_list(self, *args: Any, **kwargs: Any) -> Any: ...

    def layer_show(self, *args: Any, **kwargs: Any) -> Any: ...

    def note_copy(self, *args: Any, **kwargs: Any) -> Any: ...

    def note_delete(self, *args: Any, **kwargs: Any) -> Any: ...

    def note_exists(self, *args: Any, **kwargs: Any) -> Any: ...

    def note_get(self, *args: Any, **kwargs: Any) -> Any: ...

    def note_list(self, *args: Any, **kwargs: Any) -> Any: ...

    def note_set(self, *args: Any, **kwargs: Any) -> Any: ...

    def parameter_copy(self, *args: Any, **kwargs: Any) -> Any: ...

    def parameter_delete(self, *args: Any, **kwargs: Any) -> Any: ...

    def parameter_exists(self, *args: Any, **kwargs: Any) -> Any: ...

    def parameter_list(self, file_: str | None = ..., **kwargs: Any) -> Any: ...

    def parameter_set(
            self,
            name: str,
            value: Any,
            file_: str | None = ...,
            type_: str | None = ...,
            no_create: bool | None = ...,
            designate: bool | None = ...,
            **kwargs: Any,
    ) -> Any: ...

    def parameter_set_designated(self, *args: Any, **kwargs: Any) -> Any: ...

    def server_pwd(self, *args: Any, **kwargs: Any) -> Any: ...

    def view_activate(self, *args: Any, **kwargs: Any) -> Any: ...

    def view_list_exploded(self, *args: Any, **kwargs: Any) -> Any: ...

    def view_list(self, *args: Any, **kwargs: Any) -> Any: ...

    def view_save(self, *args: Any, **kwargs: Any) -> Any: ...

    def windchill_authorize(self, *args: Any, **kwargs: Any) -> Any: ...

    def windchill_clear_workspace(self, *args: Any, **kwargs: Any) -> Any: ...

    def windchill_create_workspace(self, *args: Any, **kwargs: Any) -> Any: ...

    def windchill_delete_workspace(self, *args: Any, **kwargs: Any) -> Any: ...

    def windchill_file_checked_out(self, *args: Any, **kwargs: Any) -> Any: ...

    def windchill_get_workspace(self, *args: Any, **kwargs: Any) -> Any: ...

    def windchill_list_workspace_files(self, *args: Any, **kwargs: Any) -> Any: ...

    def windchill_list_workspaces(self, *args: Any, **kwargs: Any) -> Any: ...

    def windchill_server_exists(self, *args: Any, **kwargs: Any) -> Any: ...

    def windchill_set_server(self, *args: Any, **kwargs: Any) -> Any: ...

    def windchill_set_workspace(self, *args: Any, **kwargs: Any) -> Any: ...

    def windchill_workspace_exists(self, *args: Any, **kwargs: Any) -> Any: ...
