%-----------------------------------------------------------------
% Title Page Description - Front Side (Inclusion File .inc)
%-------------------------------------------------------------------

\begin{titlepage}
    \thispagestyle{empty}
    \oddsidemargin4mm
    \evensidemargin4mm

    \vspace*{10mm}
    \vspace*{-30mm}

    \begin{minipage}[b][3cm][t]{0.45\textwidth}
        \includegraphics[width=45mm]{HKA_MMT_Wortmarke_RGB.jpg}
    \end{minipage}
    \hfill 
    \begin{minipage}[b][3cm][t]{0.45\textwidth}
        \hfill 
        \includegraphics[width=40mm]{HKA_MMT_Bildmarke-h_RGB.jpg}
    \end{minipage}

    \vspace{10mm}

    \begin{center}
        \sffamily
        {\huge \bfseries Development Project

Connecting CAD to Digital Twins\\}

        \vspace*{10mm}

        \begin{minipage}[b][8cm][t]{\textwidth}
            \centering
            \includegraphics[width=150mm]{Titelbild.png}
        \end{minipage}

        \vspace*{30mm}

        \large As of: \today

        \vspace*{10mm}

        Authors:\\
        Martin Deichelbohrer\\
        Mika Schmitt\\
        Tobias Halfmann\\

        \vspace*{10mm}

        Supervisor:\\
        Prof. Dr. Michael Hoffmeister\\
    \end{center}

\end{titlepage}