%%
%% Explanation and Blocking Notice
%%
%% Caution when removing \\ and blank lines
%%
%% Blocking notice only if absolutely necessary!
%%------------------------------------------------------------------------
%
\setcounter{page}{3}       % adjust: if 1 page then 2
\pagestyle{scrheadings}    % header and footer

\chapter*{}
\centerline{\Large \textsf{\textbf{Declaration of Originality}}} \label{Erklaerung}%\\
\vspace*{2ex}
%
We hereby certify that we prepared this work independently, have fully and precisely listed all aids used, and have clearly identified everything that was taken from the work of others, either unchanged or with modifications.\\

We further declare that when using IT/AI-assisted writing tools we have fully listed these tools in the section \enquote{Resources and Tools}, including their product name, our source, and an overview of the functionality used in the scope of this study project.

We confirm that we worked independently throughout the preparation of the submitted assessment and, when using IT/AI-assisted writing tools, exercised steering control.



\vspace*{4ex}
Karlsruhe, \today \\

\vspace*{4ex}
Signatures:\\

\vspace{1cm}
\noindent\rule{6cm}{0.4pt}\\

\vspace{1cm}
\noindent\rule{6cm}{0.4pt}\\

\vspace{1cm}
\noindent\rule{6cm}{0.4pt}\\

\vspace{2cm}

%--------------------------------------------------------------
